version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: undercover-frontend
    restart: unless-stopped
    ports:
      - "3000:3000"  # Next.js app
    environment:
      - NODE_ENV=production
      - SOCKET_URL=http://backend:3001  # Connect to backend service
      - NEXT_PUBLIC_SOCKET_URL=http://47.120.24.209:3001
    volumes:
      - frontend-data:/app/data
    networks:
      - app-network
    depends_on:
      - backend

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: undercover-socket
    restart: unless-stopped
    ports:
      - "3001:3001"  # Socket.io server
    environment:
      - NODE_ENV=production
      - SOCKET_PORT=3001
    volumes:
      - backend-data:/app/data
    networks:
      - app-network

volumes:
  frontend-data:
    driver: local
  backend-data:
    driver: local

networks:
  app-network:
    driver: bridge